server:
  port: 8084
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-trade
  swagger:
    title: 订单服务接口
    package: com.hmall.trade.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://localhost:8090
      http-method-specify: true