server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true   #开启feign支持sentinel
hm:
  db:
    database: hm-cart
  swagger:
    title: 购物车服务接口
    package: com.hmall.cart.controller
