server:
  port: 8083
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-user
  swagger:
    title: 用户服务接口
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
