server:
  port: 8085
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-pay
  swagger:
    title: 交易服务接口
    package: com.hmall.pay.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://localhost:8090
      http-method-specify: true